#!/bin/sh
set -eux

: plash data init populates dir
export PLASH_DATA=$(mktemp -d)
plash data init
out=$(ls -A $PLASH_DATA)
test -n "$out"

: calling plash data init two times does not crash
export PLASH_DATA=$(mktemp -d)
plash data init
plash data init

: plash data init creates dir
tmp=$(mktemp -d)
export PLASH_DATA=$tmp/myplashdata
plash data init
out=$(ls -A $tmp/myplashdata)
test -n "$out"
