language: generic

install:

  # install plash and dependencies
  - sudo apt-get install python3-pip
  - sudo pip3 install plash

cache:
  directories:
    - ~/plashcache

script:

  # load the plash cache
  - sudo -E ./ci

  - sudo -E plash run --include-string " $BUILD" -- ./ci

  # save the plash cache
  - sudo tar -cf ~/plashcache/data.tar /var/lib/plash
