language: generic
env:
  - BUILD='-i ubuntu --apt python3-pip'

install:

  # install plash and dependencies
  - sudo apt-get install python3-pip
  - sudo pip3 install plash

cache:
  directories:
    - ~/plashcache

script:

  # load the plash cache
  - sudo tar -xf ~/plashcache/data.tar -C / || sudo plash init

  - sudo plash-exec
  - sudo -E plash-exec
  - whereis plash-exec
  - sudo whereis plash-exec
  - plash-exec
  - sudo -E env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin plash run --include-string " $BUILD" -- ./ci

  # save the plash cache
  - sudo tar -cf ~/plashcache/data.tar /var/lib/plash
