language: generic

install:

  # install plash and dependencies
  - sudo apt-get install python3-pip
  - sudo pip3 install plash

cache:
  directories:
    - ~/plashcache

script:

  # load the plash cache
  - sudo plash init
  - sudo -E ./ci

  # save the plash cache
  - sudo tar -cf ~/plashcache/data.tar /var/lib/plash
