language: python
sudo: enabled
python:
  - "3.5"
  - "3.6"
  - "pypy3.5"

script:
  - sudo misc/runtests

deploy:
  - provider: pypi
    user: $PYPI_USER
    password: $PYPI_PASSWORD
    distributions: "bdist_wheel"
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = 3.6
  - provider: script
    script: git tag 0.$TRAVIS_BUILD_NUMBER -m "https://pypi.org/project/plash/0.$TRAVIS_BUILD_NUMBER" && git push https://${GH_TOKEN}@github.com/ihucos/plash.git --tags
    on:
      branch: master
      condition: $TRAVIS_PYTHON_VERSION = 3.6
