#!/usr/bin/env python3
#
# usage: plash run CONTAINER [ CMD1 [ CMD2 ... ] ]
# Run a container. Default command is the shell
# started.

import os
import shlex
import sys
from subprocess import check_call

from plash import utils
from plash.utils import (die_with_usage, get_plash_data, handle_build_args,
                         handle_help_flag, nodepath_or_die)

handle_help_flag()
handle_build_args()

try:
    container_id, *cmd = sys.argv[1:]
except ValueError:
    die_with_usage()

utils.execsub(utils.get_plash_path(), 'runopts', '--', container_id, *cmd)
