#!/usr/bin/env python3
# usage: plash clean
# clean older containers

import os
from time import time
import sys
from plash import utils
import shutil
import subprocess

utils.handle_help_flag()
utils.assert_initialized()

TIME_UNITS = {
    's': 1, # seconds
    'm': 60, # minutes
    'h': 60 * 60, # hours
    'd': 60 * 60 * 24, # days
    'w': 60 * 60 * 24 * 7, # weeks
}
DEFAULT_ARG = '4w'

time_diff = 0
for arg in sys.argv[1:] or [DEFAULT_ARG]:
    try:
        unit = arg[-1].lower()
        amount = int(arg[:-1])
        time_diff += TIME_UNITS[unit] * amount
    except (ValueError, IndexError, KeyError):
        utils.die('args must be like /[0-9][smhdw]/ not {}'.format(repr(arg)))

expire_older_than = time() - time_diff

index_dir = os.path.join(utils.get_plash_data(), 'index')
for container_id in os.listdir(index_dir):
    if container_id == '0': # the special root container, don't touch that one
        continue
    abs_file = os.path.join(index_dir, container_id)
    try:
        mtime = os.stat(abs_file).st_mtime
    except FileNotFoundError:
        # link is pointing to nowhere because the build data was deleted
        # we can safely delete the link now
        try:
            os.unlink(abs_file)
        except FileNotFoundError:
            pass # already deleted by other process
        continue

    if mtime < expire_older_than:
        subprocess.call(['plash-rm', container_id]) # plash rm removes it atomically
