#!/usr/bin/env python3
import os
import sys

import plash
from plash import utils
from plash.utils import die


def die_helping():
    print(
        'Plash is a lean container build and run engine, try `plash help`',
        file=sys.stderr)
    sys.exit(1)


try:
    subcommand = sys.argv[1]
except IndexError:
    die_helping()
if subcommand in ('-h', '--help'):
    die_helping()

try:
    utils.execsub('plash-' + subcommand, *sys.argv[2:])
except FileNotFoundError:
    die('no such command: {} (try `plash help`)'.format(subcommand))
