#!/bin/sh
# usage: plash disk-usage
# prints plash's disk usage
set -e
PLASH_DATA=$(python3 -c 'from plash.utils import get_plash_data; print(get_plash_data())')
du -sh "$PLASH_DATA"
du -sh "$PLASH_DATA"/tmp
