#!/usr/bin/env python3
# usage: plash shrink
# Delete half of the less used containers

import os
import math
import sys
import shutil
import subprocess
from plash import unshare, utils

# allows changing subuids in the fs
unshare.unshare_if_user()

DELETE_PERCENT = 50

# we need to clean the index links since we suppose that each represents an container
subprocess.call(['plash-data_clean', '--clean-index', '--quiet'])

modified_times = []
index_dir = os.path.join(utils.get_plash_data(), 'index')
containers = os.listdir(index_dir)
containers.remove('0') # don't mess around with the special root container
for container_id in containers:
    index_path = os.path.join(index_dir, container_id)
    if not container_id.isdigit():
        print('bad {}'.format(index_path), file=sys.stderr)
    st = os.lstat(index_path)
    modified_times.append((container_id, st.st_mtime))

def key(item):
    # get first all containers that are not sticky (timestamp is not zero),
    # then all containers with the oldest modification timestamp,
    # if modification timestamps are equal, get the containers with
    # the lowest id last so we don't delete containers with children.
    container_id, timestamp = item
    if timestamp:
        sticky = 0
    else:
        sticky = 1
    return sticky, timestamp, -int(container_id)

modified_times.sort(key=key)
sorted_containers = [i[0] for i in modified_times]

delete_until_index = int(math.ceil((DELETE_PERCENT / 100.0) * len(sorted_containers)))
delete_containers = sorted_containers[:delete_until_index]
deleted_counter = 0
for container_id in delete_containers:

    # delete the container
    index_path = os.path.join(index_dir, container_id)
    node = os.readlink(index_path)
    tmp = utils.mkdtemp()
    try:
        os.rename(node, tmp)
    except FileNotFoundError:
        # already deleted build, delete index
        os.unlink(index_path)
    shutil.rmtree(tmp)
    deleted_counter += 1

print('deleted {} of {} container(s)'.format(deleted_counter, len(sorted_containers)), file=sys.stderr)
